### ISSUE TITLE
std::vector not declared

### ISSUE THREAD

**Issue by cppcooper** [BCCF-UBCO-AD/Exercise1#9]
Looks like feat-files was missing an `#include <vector>` which escaped me and anyone else who reviewed it. How on earth did this manage to build on Brian's machine?

**Comment by cppcooper** [comment]
The fix could be included in @raouft PR https://github.com/BCCF-UBCO-AD/Exercise1/pull/2

**Comment by raouft** [comment]
Yes I'll add this to my branch

**Comment by raouft** [comment]
Added: bccd981
